# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_issue_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='begin_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='conference_type',
            field=models.CharField(blank=True, choices=[('earlybird', '얼리버드'), ('regular', '일반'), ('company', '법인'), ('patron', '개인후원')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='event_type',
            field=models.CharField(choices=[('conference', '컨퍼런스'), ('tuturial', '튜토리얼'), ('young', '영코더'), ('babycare', '아이돌봄')], default='conference', max_length=15),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([('event_type', 'conference_type')]),
        ),
    ]
