# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_add_extra_fields_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('card-korean', 'Credit Card only for Korean'), ('card-foreign', 'Credit Card for Foreign'), ('vbank', 'Virtual Bank Transfer')], default='card-korean', max_length=20),
        ),
    ]
