# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_add_extra_fields_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('personal', '일반'), ('group', '단체')], default='personal', max_length=20),
        ),
    ]
