# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20180601_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='additional_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
