# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20180607_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='top_size',
            field=models.CharField(blank=True, choices=[('small', 'S(85)'), ('medium', 'M(90)'), ('large', 'L(95)'), ('xlarge', 'XL(100)'), ('2xlarge', '2XL(105)'), ('3xlarge', '3XL(110)'), ('4xlarge', '4XL(115)')], default=None, max_length=20, null=True),
        ),
    ]
