# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-15 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20180607_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='event_type',
            field=models.CharField(choices=[('conference', '컨퍼런스'), ('tutorial', '튜토리얼'), ('young', '영코더'), ('babycare', '아이돌봄')], default='conference', max_length=15),
        ),
    ]
