# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20180715_2205'),
        ('registration', '0027_auto_20180708_2058'),
    ]

    operations = [
    ]
