# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20180708_2058'),
        ('pyconkr', '0020_auto_20180611_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialproposal',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Option', verbose_name='구매 티켓 종류'),
        ),
    ]
