# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20180708_2058'),
        ('pyconkr', '0020_auto_20180611_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialproposal',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='begin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Option', verbose_name='구매 티켓 종류'),
        ),
    ]
